### ISSUE TITLE
Use Symfony recipes

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-symfony#78]
Docs: https://github.com/symfony/recipes/blob/master/README.rst

Related to:
- https://github.com/meilisearch/meilisearch-symfony/issues/55#issuecomment-786641015
- https://github.com/meilisearch/meilisearch-symfony/issues/55#issuecomment-826153870

**Comment by codedge** [comment]
I already opened a [PR](https://github.com/symfony/recipes-contrib/pull/1128) at the [`symfony/recipes`](https://github.com/symfony/recipes) repository.

It currently fails because `doctrine/orm` is only a dev-requirement but actually is needed to be injected in the [`MeiliSearchImportCommand`](https://github.com/meilisearch/meilisearch-symfony/blob/main/src/Command/MeiliSearchImportCommand.php#L52). This issue is tackled in PR #76.

**Comment by curquiza** [comment]
@codedge are we still waiting for https://github.com/symfony/recipes-contrib/pull/1188? :)

**Comment by ker0x** [comment]
Hello @curquiza, @brunoocasali 

Would you still be interested in getting a recipe for the bundle? If so, I would be happy to submit a PR in the recipes-contrib repository!

**Comment by brunoocasali** [comment]
Hi, @ker0x yes that would be great! :D. Do you need anything from the Meilisearch side?

**Comment by ker0x** [comment]
Hello @brunoocasali

I have opened a PR: symfony/recipes-contrib#1494

If you or anyone else on the Meilisearch team can take a look and give feedback, it would be appreciated 👍.

**Comment by ker0x** [comment]
Well, that was quick, the PR was merged 😄!

You can close this issue 😉!

**Comment by brunoocasali** [comment]
Amazing, thanks @ker0x 🎉 🎉
